// Corporate content approved by the brief. Routes and visual assets are retained.
export const site = {
  name: 'JCAR Labs Inc.',
  origin: 'https://jcarlabs.com',
  socialImage: 'https://jcarlabs.com/assets/images/hero-image-6.jpg',
  title: 'JCAR Labs Inc. — Ingeniería de Software, SaaS e IA',
  description: 'Ingeniería de software para negocios: productos SaaS, modernización de sistemas legacy, IA transmodal y agentes, arquitectura cloud y auditoría de código.',
  technologies: ['Python', 'JavaScript', 'React', 'Node.js', 'SQL', 'Java', 'PHP'],
};

export const services = [
  { route: '/services/desarrollo-web', number: '01', label: 'SOFTWARE & SAAS', title: 'Desarrollo de Software a Medida & Productos SaaS',
    description: 'Desarrollo de software a medida y productos SaaS. Del proceso de negocio a una plataforma preparada para crecer.',
    sourceTitle: 'Beyond AI Aesthetics: What Human-Led Digital Art Means Now',
    sourceDescription: 'AI didn’t replace creativity. It reshaped it — forcing artists to redefine what human originality truly means.',
    oldTitle: 'Desarrollo Web', tags: ['React', 'Node.js', 'SQL', 'Producto SaaS'],
    article: [
      'Desarrollo de Software a Medida & Productos SaaS. Convertimos necesidades de negocio en productos digitales que pueden evolucionar con sus usuarios. Partimos de los procesos, los datos y las decisiones que el software debe facilitar.\n\nDefinimos el alcance, validamos los flujos y construimos una base mantenible. La arquitectura, las pruebas y la seguridad acompañan al producto desde el inicio.',
      'Producto y lógica de negocio',
      'Un producto útil empieza por entender quién lo usa y qué necesita resolver. Identificamos reglas de negocio, roles y recorridos antes de decidir cómo implementarlos.',
      'El alcance se organiza por valor y por dependencias reales.',
      'Diseñamos software a medida para conectar la experiencia de usuario con las operaciones. Cada módulo tiene una responsabilidad clara y cada dato, un lugar definido dentro del sistema.',
      'Para productos SaaS, planificamos la separación de clientes, los permisos y la evolución de funcionalidades según el modelo del negocio.',
      'Una base que puede evolucionar',
      'El ecosistema combina React y JavaScript en la experiencia de usuario con Node.js, Python, Java o PHP en los servicios, según las necesidades del producto. SQL conecta la información con los procesos.',
      'La elección técnica responde al contexto: integraciones existentes, experiencia del equipo, mantenimiento y carga esperada. Documentamos las decisiones para que el producto pueda continuar creciendo.',
      'Interfaz y reglas de negocio conectadas.',
      'Datos consistentes y accesos definidos.',
      'Una base preparada para nuevas versiones.',
      'Calidad durante todo el desarrollo',
      'La seguridad y la mantenibilidad forman parte del diseño del producto.',
      'Validamos los recorridos críticos, los permisos y las integraciones antes de cada entrega. Las pruebas y la revisión de código permiten detectar problemas y reducir el riesgo de cambios posteriores.',
      'Software pensado para operar y evolucionar.',
      'Entregamos una base comprensible: responsabilidades claras, documentación y criterios para evaluar su comportamiento. El alcance de cada etapa se acuerda con el negocio.',
      '¿Qué proceso necesita una mejor herramienta?',
      'Conversemos sobre el producto que quieres construir.',
    ] },
  { route: '/services/inteligencia-artificial', number: '02', label: 'IA, AGENTES & LLMOPS', title: 'Integración de IA Transmodal, Agentes y LLMOps',
    description: 'Integración de IA transmodal, agentes y LLMOps. Conectamos modelos, datos y herramientas con procesos de negocio.',
    sourceTitle: 'When Images Begin to Listen: The Quiet Power of Responsive Art',
    sourceDescription: 'Interactive work is evolving beyond touchscreens and gimmicks. The most compelling contemporary pieces now respond subtly — to sound, environment, presence, and emotion.',
    oldTitle: 'Inteligencia Artificial', tags: ['Python', 'APIs', 'Agentes', 'LLMOps'],
    article: [
      'Integración de IA Transmodal, Agentes y LLMOps. Diseñamos soluciones que conectan texto, imágenes, audio y documentos según las capacidades del modelo y la necesidad del negocio.\n\nLos agentes coordinan herramientas y tareas dentro de límites explícitos. LLMOps aporta evaluación, seguimiento y control de versiones para pasar de una demostración a una operación que pueda supervisarse.',
      'IA conectada con el negocio',
      'Comenzamos por un caso de uso concreto:',
      'Comprender. Asistir. Automatizar.',
      'Identificamos qué información necesita el sistema y qué decisiones requieren revisión humana.',
      'La integración transmodal permite trabajar con distintos tipos de información sin perder el contexto del proceso. La solución se diseña alrededor de los datos disponibles y sus restricciones.',
      'Texto y documentación del negocio.',
      'Imágenes y archivos relevantes para la tarea.',
      'Audio y otros formatos cuando el caso de uso lo requiere.',
      'Cada entrada tiene una finalidad definida.',
      'La IA se conecta con sistemas existentes mediante APIs y servicios. Delimitamos qué datos puede consultar y qué acciones puede ejecutar, con trazabilidad de las operaciones relevantes.',
      'Agentes con responsabilidades claras',
      'Un agente puede consultar información, utilizar herramientas y coordinar pasos de un flujo. Definimos su alcance, sus permisos y las condiciones en las que debe pedir intervención humana.',
      'La autonomía se diseña con límites.',
      'Usamos Python y servicios API como parte del ecosistema de integración. La selección de modelos responde a calidad, latencia, coste y tratamiento de datos, evaluados para cada proyecto.',
      'La operación necesita criterios visibles.',
      'Calidad de respuesta.',
      'Tiempo de ejecución.',
      'Uso de recursos.',
      'Y un camino de revisión cuando el sistema no tiene suficiente información.',
      'LLMOps para mejorar con evidencia',
      'Los modelos y los datos cambian.',
      'Preparamos evaluaciones con ejemplos del proceso real, versionamos instrucciones y revisamos los resultados antes de incorporar cambios. El objetivo es detectar degradaciones y hacer la operación comprensible.',
      '“Cada cambio debe poder evaluarse.”',
      'Las trazas ayudan a entender cada ejecución.',
      'Se revisan los errores.',
      'Se contrastan las respuestas.',
      'Se ajustan los límites.',
      'La supervisión permite mejorar la solución sin convertir cada actualización en una apuesta. Documentamos los criterios y las decisiones que afectan su funcionamiento.',
      'IA integrada con criterio y seguimiento.',
    ] },
  { route: '/services/desarrollo-full-stack', number: '03', label: 'CLOUD & APIS', title: 'Arquitectura Cloud, APIs & Microservicios',
    description: 'Arquitectura cloud, APIs y microservicios. Diseñamos servicios conectados, observables y preparados para evolucionar.',
    sourceTitle: 'The Rise of Experiential Minimalism in Contemporary Exhibitions',
    sourceDescription: 'Instead of spectacle, galleries are embracing controlled intensity — restrained environments with powerful psychological impact.',
    oldTitle: 'Desarrollo Full Stack', tags: ['Node.js', 'Java', 'Python', 'APIs'],
    article: [
      'Arquitectura Cloud, APIs & Microservicios. Diseñamos la relación entre servicios, datos e infraestructura para que el sistema responda a las necesidades del negocio.\n\nDefinimos límites, contratos e integraciones con criterios de seguridad, operación y crecimiento. Elegimos una arquitectura acorde con la complejidad real y con la capacidad del equipo que la mantendrá.',
      'Servicios con límites claros',
      'Identificamos los dominios del negocio, los flujos de información y las dependencias. Esa lectura permite definir responsabilidades y evitar que cada cambio afecte al sistema completo.',
      'Las APIs establecen contratos entre equipos y aplicaciones. Diseñamos entradas, respuestas, autenticación, tratamiento de errores y evolución de versiones para hacer predecible la integración.',
      'Los microservicios se evalúan cuando aportan independencia de despliegue u operación. Consideramos también el coste de coordinación, las llamadas de red y la consistencia de datos.',
      'Cada servicio debe tener una razón para existir.',
      'Evolución y operación',
      'El ecosistema de servicios puede combinar Node.js, Java, Python y PHP según el contexto. SQL sostiene la información estructurada; React conecta los servicios con la experiencia de usuario.',
      'Planificamos entornos, configuración, despliegue y observabilidad. El proveedor cloud y las herramientas se definen con el proyecto, considerando requisitos operativos y restricciones del negocio.',
      'La arquitectura se valida en funcionamiento.',
      'Con señales que el equipo pueda interpretar.',
      'Registros, métricas y documentación ayudan a investigar incidentes y a priorizar mejoras con información del sistema.',
      'Seguridad e integraciones',
      'Definimos permisos, manejo de secretos y validación de entradas desde los límites del sistema. Revisamos los datos que circulan y las responsabilidades de cada integración.',
      'Diseñamos cómo responder a fallos: tiempos de espera, reintentos acotados y recuperación. La disponibilidad se planifica de acuerdo con el alcance y las condiciones de operación.',
      'Integraciones comprensibles y controladas.',
      'Una arquitectura mantenible permite incorporar nuevas capacidades sin perder visibilidad sobre el conjunto. Dejamos decisiones y contratos documentados para facilitar el trabajo del equipo.',
      'Construyamos una base que acompañe al negocio.',
    ] },
  { route: '/services/software-empresarial', number: '04', label: 'SISTEMAS LEGACY', title: 'Modernización e Ingeniería de Sistemas Legacy',
    description: 'Modernización e ingeniería de sistemas legacy. Evolucionamos aplicaciones existentes con una transición gradual y verificable.',
    sourceTitle: 'Why Motion-First Art Is Defining The Next Creative Era',
    sourceDescription: 'Static visuals are no longer enough. Motion-first thinking is reshaping art, branding, and digital experiences — here’s why the shift matters.',
    oldTitle: 'Software Empresarial', tags: ['Java', 'PHP', 'SQL', 'Modernización'],
    article: [
      'Modernización e Ingeniería de Sistemas Legacy. El software existente contiene reglas, integraciones y conocimiento del negocio que deben entenderse antes de cambiarlo.\n\nAnalizamos el sistema, hacemos visibles sus dependencias y definimos una transición por etapas. El objetivo es mejorar su capacidad de evolución manteniendo bajo control la continuidad operativa y los datos que utiliza.',
      'Entender antes de transformar',
      'Revisamos código, datos, interfaces y procesos de operación. Documentamos las funciones críticas y las dependencias para distinguir qué debe conservarse, qué puede aislarse y qué conviene reemplazar.',
      'La ingeniería del sistema legacy recupera conocimiento que suele estar repartido entre el código y las personas. Convertimos ese contexto en criterios para decidir el siguiente cambio.',
      'Antes de intervenir, establecemos una referencia del comportamiento actual. Las pruebas de caracterización ayudan a detectar variaciones en reglas y recorridos importantes.',
      'La modernización puede incluir separar módulos, exponer APIs, actualizar componentes o migrar partes del sistema. El plan responde a riesgos y necesidades, no a una sustitución automática de todo el código.',
      'Una transición por etapas',
      'Ordenamos los cambios por impacto y dependencia. Cada etapa define qué se modifica, cómo se valida y qué condiciones deben cumplirse para continuar.',
      'La continuidad del negocio guía las decisiones.',
      'Trabajamos con el ecosistema existente, incluyendo Java, PHP y SQL cuando forman parte de la solución. Incorporamos tecnologías como Node.js, Python o React donde aportan una mejora justificada.',
      'La transición de datos requiere controles propios: correspondencia de estructuras, validación de resultados y mecanismos de recuperación. Las integraciones también se verifican antes de pasar a producción.',
      'Cada avance debe dejar el sistema más comprensible.',
      'Y ofrecer al equipo una base para continuar.',
      'Conservar el conocimiento del negocio',
      'Modernizar también implica documentar decisiones y reducir dependencias difíciles de mantener. Buscamos que las personas puedan entender el sistema, investigar fallos y trabajar sobre él con mayor claridad.',
      'Evolución con continuidad.',
      'Acordamos el alcance de la transición, los criterios de aceptación y las responsabilidades operativas. La nueva arquitectura se conecta con la realidad del sistema que ya sostiene al negocio.',
    ] },
  { route: '/services/auditoria-de-codigo', number: '05', label: 'AUDITORÍA DE CÓDIGO', title: 'Consultoría de Arquitectura y Auditoría de Código',
    description: 'Consultoría de arquitectura y auditoría de código. Convertimos hallazgos técnicos en decisiones y prioridades para el negocio.',
    sourceTitle: 'Why Slowness Is Becoming a Radical Artistic Choice',
    sourceDescription: 'In a culture obsessed with speed, instant gratification, and constant refresh, artists are turning to slowness — not as nostalgia, but as resistance.',
    oldTitle: 'Integraciones SUNAT', tags: ['Arquitectura', 'Código', 'Seguridad', 'Mantenibilidad'],
    article: [
      'Consultoría de Arquitectura y Auditoría de Código. Revisamos cómo está construido un sistema y qué necesita para continuar evolucionando.\n\nConectamos decisiones técnicas con el contexto del negocio: operación, crecimiento, riesgos y capacidad del equipo. La revisión produce hallazgos explicados y una hoja de ruta priorizada, con un alcance acordado desde el inicio.',
      'Una revisión con contexto',
      'La auditoría empieza por definir el alcance.',
      'Qué componentes se revisan.',
      'Qué procesos son críticos.',
      'Qué preguntas necesita responder el equipo para decidir sobre la siguiente etapa del producto o de la plataforma.',
      'El código se interpreta dentro del sistema.',
      'Sus responsabilidades.',
      'Sus dependencias.',
      'Sus puntos de cambio.',
      'Analizamos la organización del código, los contratos y el tratamiento de datos. Contrastamos la implementación con los requisitos y las restricciones que debe atender.',
      'Los hallazgos necesitan evidencia y contexto.',
      'Decisiones que se pueden ejecutar',
      'Una revisión es útil cuando permite ordenar el trabajo.',
      'Riesgo e impacto.',
      'Esfuerzo y dependencias.',
      'Prioridad y secuencia.',
      'Documentamos los problemas observados y las alternativas de mejora. Diferenciamos acciones inmediatas de cambios que requieren una transición o una decisión de producto.',
      'El resultado es una hoja de ruta.',
      'Comprensible.',
      'Priorizada.',
      'Justificada.',
      'Acorde con el contexto.',
      'El equipo recibe criterios para actuar y para verificar si los cambios resuelven el problema identificado.',
      'Seguridad y mantenibilidad',
      'Revisamos límites y responsabilidades.',
      'El análisis puede abarcar autenticación, autorización, validación de entradas, manejo de errores y dependencias. Las conclusiones se vinculan con el código y el alcance efectivamente revisados.',
      'El ecosistema documentado incluye JavaScript, React, Node.js, Python, Java, PHP y SQL. Definimos la profundidad de revisión según los componentes del proyecto.',
      'También evaluamos claridad y facilidad de cambio.',
      'Una auditoría de código aporta información para decidir; el alcance específico determina qué aspectos pueden evaluarse y qué validaciones adicionales necesita el sistema.',
      'Conversemos sobre lo que necesitas conocer de tu software.',
    ] },
];

// Replacements for template text and content layer.
export const sharedCopy = {
  // Navigation & Core Identity
  'HOME': 'INICIO',
  'WORK': 'PROYECTOS',
  'ABOUT': 'NOSOTROS',
  'THOUGHTS': 'SERVICIOS',
  'CONTACT': 'CONTACTO',
  'PRIVACY POLICY': 'POLÍTICA DE PRIVACIDAD',
  'TERMS OF USE': 'TÉRMINOS DE USO',
  'VERTICAL': 'JCAR LABS',
  'ADAM KNOXVILLE': 'JCAR LABS INC',
  'ADAM KNOXVILLE / VERTICAL': 'JCAR LABS INC',
  'VISUAL ARTIST/CREATOR': 'DESARROLLO WEB · SOFTWARE · IA',
  'INDEPENDENT VISUAL ARTIST': 'CEO de Jcar Labs Inc.',
  'EXPLORE': 'DESCUBRIR',

  // Hero section copy
  'I BREAK THINGS': 'CREAMOS SOLUCIONES',
  'I break things': 'Creamos soluciones',
  'TO SEE WHAT': 'DIGITALES QUE',
  'to see WHAT': 'digitales que',
  'THEY ARE MADE OF': 'HACEN CRECER NEGOCIOS',
  'they are made of': 'hacen crecer negocios',
  'PHASE/BREAK': 'FASE/IDEA',
  'PHASE/BUILD': 'FASE/DISEÑO',
  'PHASE/BEND': 'FASE/DESARROLLO',
  'PHASE/RELEASE': 'FASE/ESCALA',
  'IDX/AK': 'JCAR/LABS',

  // Corporate Messaging
  'DESARROLLO WEB · SOFTWARE · IA': 'SOFTWARE · SISTEMAS · IA',
  'EQUIPO DE DESARROLLO Y TECNOLOGÍA': 'INGENIERÍA DE SOFTWARE PARA NEGOCIOS',
  'CREAMOS SOLUCIONES': 'SOFTWARE',
  'DIGITALES QUE': 'PARA TU',
  'HACEN CRECER NEGOCIOS': 'NEGOCIO',
  'LA TECNOLOGÍA CONVIERTE IDEAS EN EXPERIENCIAS ÚTILES, MEMORABLES Y PREPARADAS PARA CRECER.': 'INGENIERÍA DE SOFTWARE PARA CREAR PRODUCTOS, MODERNIZAR SISTEMAS Y CONECTAR EL NEGOCIO CON IA.',
  'TRABAJAMOS ENTRE ESTRATEGIA, DISEÑO, SOFTWARE E INTELIGENCIA ARTIFICIAL PARA DAR FORMA A CADA SOLUCIÓN.': 'UNIMOS SOFTWARE A MEDIDA, ARQUITECTURA Y OPERACIÓN PARA CONSTRUIR SISTEMAS ESCALABLES Y SEGUROS.',
  'NO ES SOLO UN PORTAFOLIO.': 'INGENIERÍA CON PROPÓSITO.',
  'ES UNA MUESTRA VIVA DE CÓMO JCAR LABS TRANSFORMA NECESIDADES REALES EN PRODUCTOS DIGITALES.': 'CADA SOLUCIÓN PARTE DEL NEGOCIO Y SE SOSTIENE EN CÓDIGO, DATOS Y DECISIONES DE ARQUITECTURA.',
  'CREAMOS EXPERIENCIAS WEB CLARAS, RÁPIDAS Y DISEÑADAS PARA CONVERTIR INTERÉS EN RESULTADOS.': 'CONSTRUIMOS PRODUCTOS SAAS Y SOFTWARE A MEDIDA CON UNA BASE PREPARADA PARA OPERAR Y EVOLUCIONAR.',
  'TECNOLOGÍA CON PROPÓSITO': 'INGENIERÍA DE PRODUCTO',
  'CAPACIDADES DIGITALES': 'ECOSISTEMA DIGITAL',
  'SOLUCIONES DISEÑADAS PARA LLEVAR TU NEGOCIO AL SIGUIENTE NIVEL.': 'SOFTWARE, ARQUITECTURA E IA PARA HACER EVOLUCIONAR TU NEGOCIO.',
  'TECNOLOGÍA CONSTRUIDA PARA RESOLVER NECESIDADES REALES.': 'ECOSISTEMA DE SOLUCIONES DIGITALES.',
  'DESARROLLO WEB': 'SOFTWARE & SAAS',
  'SOFTWARE A MEDIDA': 'SISTEMAS LEGACY',
  'INTELIGENCIA ARTIFICIAL': 'IA, AGENTES & LLMOPS',
  'AUTOMATIZACIÓN': 'CLOUD & APIS',
  'SOLUCIONES EMPRESARIALES': 'SOLUCIONES EMPRESARIALES',
  'SITIOS MODERNOS, RESPONSIVOS Y OPTIMIZADOS PARA CONVERTIR VISITAS EN OPORTUNIDADES.': 'SOFTWARE A MEDIDA Y PRODUCTOS SAAS QUE CONECTAN USUARIOS, DATOS Y PROCESOS DE NEGOCIO.',
  'CONVERTIR VISITAS EN OPORTUNIDADES': 'SOFTWARE A MEDIDA',
  'SISTEMAS ROBUSTOS Y ESCALABLES DISEÑADOS SEGÚN LOS PROCESOS DE CADA NEGOCIO.': 'MODERNIZACIÓN DE SISTEMAS LEGACY CON CAMBIOS GRADUALES, VALIDACIÓN Y CONTINUIDAD OPERATIVA.',
  'ROBUSTOS Y ESCALABLES': 'SISTEMAS LEGACY',
  'INTEGRACIÓN DE MODELOS DE IA Y AUTOMATIZACIÓN PARA ACELERAR OPERACIONES Y DECISIONES.': 'IA TRANSMODAL, AGENTES Y LLMOPS PARA CONECTAR MODELOS CON DATOS Y HERRAMIENTAS DEL NEGOCIO.',
  'IA Y AUTOMATIZACIÓN': 'AGENTES Y LLMOPS',
  'DESARROLLO INTEGRAL DESDE LA BASE DE DATOS HASTA LA EXPERIENCIA DE USUARIO.': 'ARQUITECTURA CLOUD, APIS Y MICROSERVICIOS CON CONTRATOS CLAROS Y CAPACIDAD DE EVOLUCIÓN.',
  'BASE DE DATOS': 'APIS',
  'EXPERIENCIA DE USUARIO': 'MICROSERVICIOS',
  'SOFTWARE EMPRESARIAL, INTEGRACIONES SUNAT Y HERRAMIENTAS PARA GESTIONAR OPERACIONES.': 'CONSULTORÍA DE ARQUITECTURA Y AUDITORÍA DE CÓDIGO PARA PRIORIZAR RIESGOS Y MEJORAS.',
  'INTEGRACIONES SUNAT': 'AUDITORÍA DE CÓDIGO',
  'DESARROLLO FULL STACK': 'CLOUD, APIS & MICROSERVICIOS',
  'SOFTWARE EMPRESARIAL': 'SISTEMAS LEGACY',
  'LO QUE HACEMOS': 'ECOSISTEMA TECNOLÓGICO',
  'CREAMOS SOFTWARE, EXPERIENCIAS WEB Y AUTOMATIZACIONES CON IA.': 'SOFTWARE, ARQUITECTURA E IA CONECTADOS CON TU NEGOCIO.',
  'SOMOS UN EQUIPO APASIONADO POR LA TECNOLOGÍA. CONSTRUIMOS SISTEMAS ROBUSTOS Y ESCALABLES PARA IMPULSAR NEGOCIOS EN PERÚ Y MÁS ALLÁ.': 'JCAR LABS INC. INTEGRA INGENIERÍA DE PRODUCTO, MODERNIZACIÓN E IA. TRABAJAMOS CON REACT, NODE.JS, PYTHON, JAVA, PHP Y SQL SEGÚN EL CONTEXTO.',
  'INTERFACES CLARAS Y CONSISTENTES QUE CONECTAN LA IDENTIDAD DE MARCA CON UNA EXPERIENCIA DIGITAL EFECTIVA.': 'REACT Y JAVASCRIPT PARA CONECTAR A LAS PERSONAS CON LAS FUNCIONES Y LOS DATOS DEL PRODUCTO.',
  'ARQUITECTURAS ROBUSTAS, INTEGRACIONES Y SOFTWARE A MEDIDA PARA OPERACIONES QUE NO PUEDEN DEPENDER DE IMPROVISACIONES.': 'NODE.JS, PYTHON, JAVA Y PHP PARA LOS SERVICIOS. SQL PARA ORGANIZAR LOS DATOS Y SOSTENER LOS PROCESOS.',
  'FLUJOS AUTOMATIZADOS E INTELIGENCIA ARTIFICIAL PARA REDUCIR TAREAS REPETITIVAS Y ACELERAR DECISIONES.': 'APIS, AGENTES Y LLMOPS PARA INTEGRAR CAPACIDADES DE IA CON EVALUACIÓN, TRAZABILIDAD Y SUPERVISIÓN.',
  'HABLEMOS DE TU PROYECTO Y CONVIRTAMOS TU IDEA EN UNA SOLUCIÓN DIGITAL.': 'HABLEMOS DEL SOFTWARE QUE TU NEGOCIO NECESITA CONSTRUIR O EVOLUCIONAR.',
  'ESTAMOS LISTOS PARA LLEVAR TU NEGOCIO AL SIGUIENTE NIVEL. CUÉNTANOS QUÉ NECESITAS CONSTRUIR.': 'CUÉNTANOS SOBRE TU PRODUCTO, TU SISTEMA ACTUAL O EL PROCESO QUE QUIERES CONECTAR CON IA.',
};

export const extraCopy = {
  'Thanks for reading': 'Construyamos la solución',
  'SHARE ARTICLE ON SOCIAL': 'COMPARTE ESTA SOLUCIÓN',
  'NEXT': 'SIGUIENTE', 'PREVIOUS': 'ANTERIOR',
  'December 4, 2025': 'SERVICIO 04', 'October 1, 2025': 'SERVICIO 05',
  'December 2025': 'JCAR LABS INC.',
  '4 minutes': '4 minutos', '5 minutes': '5 minutos', '3 minutes': '3 minutos', '6 mins': '6 minutos',
};
